default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: 10
  username: <%= ENV['DB_USERNAME'] || 'root' %>
  password: <%= ENV['DB_PASSWORD'] || '' %>
  reconnect: true
  host: <%= ENV['DB_HOST'] || '127.0.0.1' %>

development:
  <<: *default
  database: "hms_development"

test:
  <<: *default
  database: "hms_test"

production:
  <<: *default
  database: "hms"
